"""状态枚举与失败原因枚举"""

from enum import Enum


class TaskStatus(str, Enum):
    """论文处理状态"""
    PENDING = "PENDING"
    SUCCESS_AUTO = "SUCCESS_AUTO"
    SKIPPED_ALREADY_HAVE = "SKIPPED_ALREADY_HAVE"
    NEEDS_MANUAL = "NEEDS_MANUAL"
    FAILED_HARD = "FAILED_HARD"


class FailureReason(str, Enum):
    """失败原因枚举"""
    INVALID_DOI = "INVALID_DOI"
    METADATA_NOT_FOUND = "METADATA_NOT_FOUND"
    LANDING_PAGE_UNREACHABLE = "LANDING_PAGE_UNREACHABLE"
    PDF_NOT_FOUND = "PDF_NOT_FOUND"
    ACCESS_DENIED = "ACCESS_DENIED"
    CAPTCHA_TRIGGERED = "CAPTCHA_TRIGGERED"
    COOKIE_WALL = "COOKIE_WALL"
    SITE_LAYOUT_CHANGED = "SITE_LAYOUT_CHANGED"
    DOWNLOAD_TIMEOUT = "DOWNLOAD_TIMEOUT"
    FILE_VALIDATION_FAILED = "FILE_VALIDATION_FAILED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


class DownloadRoute(str, Enum):
    """下载策略路由"""
    OA_DIRECT = "OA_DIRECT"
    SPRINGER = "SPRINGER"
    ELSEVIER = "ELSEVIER"
    WILEY = "WILEY"
    GENERIC = "GENERIC"
    SCI_HUB = "SCI_HUB"
